version: '3'
services:
  backend:
    build: "../backend"
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    env_file: "../backend/.env.development"
    command: "yarn dev"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "../data/db:/data/db"
